import Header from "@/lib/Presentation/Component/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 dark:bg-black`}>
        <div className="flex h-full max-h-screen min-h-screen w-full flex-col">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
